import 'vuetify/styles';
import '@mdi/font/css/materialdesignicons.css';
import { createVuetify } from 'vuetify';

// Import only the components you need
import {
  VApp,
  VMain,
  VContainer,
  VRow,
  VCol,
  VBtn,
  VIcon,
  VCard,
  VCardTitle,
  VCardText,
  VCardActions,
  VAlert,
  VAppBar,
  VAppBarTitle,
  VNavigationDrawer,
  VList,
  VListItem,
  VListItemTitle,
  VFooter,
  VDivider,
  VSpacer,
  VSelect,
  VTextField,
  VTextarea,
  VSlider,
  VRangeSlider,
  VAutocomplete,
  VCombobox,
  VSwitch,
  VCheckbox,
  VRadioGroup,
  VRadio,
  VDialog,
  VSnackbar,
  VProgressLinear,
  VProgressCircular,
  VImg,
  VChip,
  VAvatar,
  VMenu,
  VTooltip,
  VTabs,
  VTab,
  VWindow,
  VWindowItem,
  VForm,
  VDataTable,
  VExpansionPanels,
  VExpansionPanel,
  VExpansionPanelTitle,
  VExpansionPanelText
} from 'vuetify/components';

// Import directives
import { Ripple } from 'vuetify/directives';

export default createVuetify({
  components: {
    VApp,
    VMain,
    VContainer,
    VRow,
    VCol,
    VBtn,
    VIcon,
    VCard,
    VCardTitle,
    VCardText,
    VCardActions,
    VAlert,
    VAppBar,
    VAppBarTitle,
    VNavigationDrawer,
    VList,
    VListItem,
    VListItemTitle,
    VFooter,
    VDivider,
    VSpacer,
    VSelect,
    VTextField,
    VTextarea,
  VSlider,
  VRangeSlider,
    VAutocomplete,
    VCombobox,
  VSwitch,
    VCheckbox,
    VRadioGroup,
    VRadio,
    VDialog,
    VSnackbar,
    VProgressLinear,
    VProgressCircular,
  VImg,
    VChip,
    VAvatar,
    VMenu,
    VTooltip,
    VTabs,
    VTab,
    VWindow,
    VWindowItem,
    VForm,
    VDataTable,
    VExpansionPanels,
    VExpansionPanel,
    VExpansionPanelTitle,
    VExpansionPanelText
  },
  directives: {
    Ripple
  },
  icons: { 
    defaultSet: 'mdi'
  },
  theme: {
    defaultTheme: 'dark',
    themes: {
      dark: {
        dark: true,
        colors: {
          primary: '#3f51b5',
          secondary: '#6ee7f0',
          accent: '#f0c419',
          surface: '#0b1b3f',
          background: '#09122a',
        },
      },
    },
  },
  defaults: {
    VBtn: { rounded: 'lg' },
    VCard: { rounded: 'lg' },
  },
});
